* 1.1

  Below is a sequence of expressions. What is the result printed by the
  interpreter in response to each expression? Assume that the sequence is to be
  evaluated in the order in which it is presented.

  #+BEGIN_SRC clojure
    10                                      ; 10
    (+ 5 3 4)                               ; 12
    (- 9 1)                                 ; 8
    (/ 6 2)                                 ; 3
    (+ (* 2 4) (- 4 6))                     ; 6
    (def a 3)                               ; 3
    (def b (+ a 1))                         ; 4
    (+ a b (* a b))                         ; 19
    (= a b)                                 ; false
    (if (and (> b a) (< b (* a b)))
        b
        a)                                  ; 4
    (cond ((= a 4) 6)
          ((= b 4) (+ 6 7 a))
          (:else 25))                       ; 16
    (+ 2 (if (> b a) b a))                  ; 6
    (* (cond ((> a b) a)
             ((< a b) b)
             (:else -1))
       (+ a 1))                             ; 16
  #+END_SRC

* 1.2

  #+BEGIN_SRC clojure
    (/ (+ 5 4 (- 2 (- 3 (+ 6 (/ 4 5)))))
       (* 3 (- 6 2) (- 2 7)))
  #+END_SRC

* 1.3

  Define a procedure that takes three numbers as arguments and returns the sum
  of the squares of the two larger numbers.

  #+BEGIN_SRC clojure
    (defn square [x] (* x x))

    (defn sum-of-squares [x y]
      (+ (square x) (square y)))

    (defn sum-of-squares-of-largest-two [x y z]
      (apply sum-of-squares
             (take 2 (reverse (sort [x y z])))))
  #+END_SRC

* 1.4

  Observe that our model of evaluation allows for combinations whose operators
  are compound expressions. Use this observation to describe the behavior of
  the following procedure:

  #+BEGIN_SRC clojure
    (define (a-plus-abs-b a b)
      ((if (> b 0) + -) a b))
  #+END_SRC

  In this method, the operator is defined as the compound expression

  #+BEGIN_SRC clojure
  (if (> b 0) + -)
  #+END_SRC

  Depending on the result of this form, we will either add or subtract a from
  b.  In practice, this means that this function always adds the absolute value
  of b to a.

* 1.5

  Ben Bitdiddle has invented a test to determine whether the interpreter he is
  faced with is using applicative-order evaluation or normal-order
  evaluation. He defines the following two procedures:

  #+BEGIN_SRC clojure
    (define (p) (p))

    (define (test x y)
      (if (= x 0)
        0
        y))
  #+END_SRC

  Then he evaluates the expression

  #+BEGIN_SRC clojure
    (test 0 (p))
  #+END_SRC

  What behavior will Ben observe with an interpreter that uses
  applicative-order evaluation? What behavior will he observe with an
  interpreter that uses normal-order evaluation? Explain your answer. (Assume
  that the evaluation rule for the special form if is the same whether the
  interpreter is using normal or applicative order: The predicate expression is
  evaluated first, and the result determines whether to evaluate the consequent
  or the alternative expression.)

  Normal order evaluation only tries to evaluate a form when it is needed.
  Since 0 is passed as the first argument to test, the if condition will
  evaluate to true, causing the function to immediately return 0.

  In applicative-order evaluation, forms are evaluated early on to avoid
  recalculation.  Since the special form

  #+BEGIN_SRC clojure
    (define p (p))
  #+END_SRC

  Is recursive, and p is passed into p, evaluating

  #+BEGIN_SRC clojure
    (test 0 (p))
  #+END_SRC

  will cause the program to never terminate.

* 1.6

  Alyssa P. Hacker doesn't see why if needs to be provided as a special
  form. ``Why can't I just define it as an ordinary procedure in terms of
  cond?'' she asks. Alyssa's friend Eva Lu Ator claims this can indeed be done,
  and she defines a new version of if:

  #+BEGIN_SRC clojure
    (define (new-if predicate then-clause else-clause)
      (cond (predicate then-clause)
            (else else-clause)))
  #+END_SRC

  Eva demonstrates the program for Alyssa:

  #+BEGIN_SRC clojure
    (new-if (= 2 3) 0 5)                    ; 5
    (new-if (= 1 1) 0 5)                    ; 0
  #+END_SRC

  Delighted, Alyssa uses new-if to rewrite the square-root program:

  #+BEGIN_SRC clojure
    (define (sqrt-iter guess x)
      (new-if (good-enough? guess x)
              guess
              (sqrt-iter (improve guess x)
                         x)))
  #+END_SRC

  What happens when Alyssa attempts to use this to compute square roots?
  Explain.

  The special form if does not use applicative-order evaluation, which means
  the else clause isn't evaluated until the interpreter deems it necessary.
  This new-if method has no such property as it is user defined.  This means
  the else clause will be called every time the new-if method is called,
  leading to infinite recursion.

* 1.7

  The good-enough? test used in computing square roots will not be very
  effective for finding the square roots of very small numbers. Also, in real
  computers, arithmetic operations are almost always performed with limited
  precision. This makes our test inadequate for very large numbers. Explain
  these statements, with examples showing how the test fails for small and
  large numbers. An alternative strategy for implementing good-enough? is to
  watch how guess changes from one iteration to the next and to stop when the
  change is a very small fraction of the guess. Design a square-root procedure
  that uses this kind of end test. Does this work better for small and large
  numbers?

  For small numbers, the limited tolerance offers insufficient resolution.  We
  stop doing further calculations much sooner than we should, leading to
  incorrect answers.

  For larger numbers, we continually lose floating-point precision.  This
  because a problem because for some arbitrarily large guess, we cannot pin
  down an answer within our given tolerance, leading to infinite recursion.

  #+BEGIN_SRC clojure
    (defn square [x] (* x x))

    (defn average [x y]
      (/ (+ x y)
         2))

    (defn good-enough? [guess previous-guess]
      (< (Math/abs (- guess previous-guess))
         0.001))

    (defn improve [guess x]
      (average guess
               (/ x guess)))

    (defn sqrt-iter [guess previous-guess x]
      (if (good-enough? guess previous-guess)
        guess
        (sqrt-iter (improve guess x)
                   guess
                   x)))

    (defn sqrt [x]
      (sqrt-iter 1.0 0 x))
  #+END_SRC

* 1.8

  Newton's method for cube roots is based on the fact that if y is an
  approximation to the cube root of x, then a better approximation is given by
  the value

  (x/y^2 + 2y) / 3

  Use this formula to implement a cube-root procedure analogous to the
  square-root procedure. (In 1.3.4 we will see how to implement Newton’s
  method in general as an abstraction of these square-root and cube-root
  procedures.)

  #+BEGIN_SRC clojure
     (defn square [x] (* x x))

     (defn good-enough? [guess previous-guess]
       (< (Math/abs (- guess previous-guess))
          0.001))

     (defn improve [guess x]
       (/ (+ (/ x (square guess)) (* 2 guess)) 3))

     (defn cube-root-iter [guess previous-guess x]
       (if (good-enough? guess previous-guess)
         guess
         (cube-root-iter (improve guess x)
                    guess
                    x)))

     (defn cube-root [x]
       (cube-root-iter 1.0 0 x))
  #+END_SRC

* 1.9

  Each of the following two procedures defines a method for adding two positive
  integers in terms of the procedures inc, which increments its argument by 1,
  and dec, which decrements its argument by 1.

  #+BEGIN_SRC clojure
    (defn + [a b]
      (if (= a 0)
        b
        (inc (+ (dec a) b))))

    ;; (+ 4 5)
    ;; (inc (+ 3 5))
    ;; (inc (inc (+ 2 5)))
    ;; (inc (inc (inc (+ 1 5))))

    ;;; We can see from this that the first method is recursive.

    (defn + [a b]
      (if (= a 0)
        b
        (+ (dec a) (inc b))))

    ;; (+ 4 5)
    ;; (+ 3 6)
    ;; (+ 2 7)

    ;;; We can see from this that the second method is iterative.
  #+END_SRC

* 1.10

  The following procedure computes a mathematical function called Ackermann’s
  function.

  #+BEGIN_SRC clojure
    (defn A [x y]
      (cond (= y 0) 0
            (= x 0) (* 2 y)
            (= y 1) 2
            :else (A (- x 1)
                     (A x (- y 1)))))
  #+END_SRC

  What are the values of the following expressions?

  #+BEGIN_SRC clojure
    (A 1 10)                                ; 1024
    (A 2 4)                                 ; 65536
    (A 3 3)                                 ; 65536
  #+END_SRC

  Consider the following procedures, where A is the procedure defined above:

  #+BEGIN_SRC clojure
    (defn f [n] (A 0 n))                    ; 2n
    (defn g [n] (A 1 n))                    ; 2^n
    (defn h [n] (A 2 n))                    ; 2^2^2 ... n times
    (defn k [n] (* 5 n n))                  ; 5n2
  #+END_SRC

  Give concise mathematical definitions for the functions computed by the
  procedures f, g, and h for positive integer values of n. For example, (k n)
  computes 5n2.

* 1.11

   A function f is defined by the rule that f(n)=n if n<3 and
   f(n)=f(n−1)+2f(n−2)+3f(n−3) if n≥3. Write a procedure that computes f by
   means of a recursive process. Write a procedure that computes f by means of
   an iterative process.

   #+BEGIN_SRC clojure
     ;;; Recursive Solution

     (defn f [n]
       (cond
         (< n 3) n
         :else (+
                (f (- n 1))
                (* 2 (f (- n 2)))
                (* 3 (f (- n 3))))))

     ;;; Iterative Solution

     (defn f [n]
       (defn iter [x z y count]
         (if (= count 0)
           x
           (iter y z (+ z (* 2 y) (* 3 x)) (- count 1))))
       (iter 0 1 2 n))
   #+END_SRC

* 1.12

  The following pattern of numbers is called Pascal’s triangle.

  #+BEGIN_EXAMPLE
             1
           1   1
         1   2   1
       1   3   3   1
     1   4   6   4   1
           . . .
  #+END_EXAMPLE

  The numbers at the edge of the triangle are all 1, and each number inside the
  triangle is the sum of the two numbers above it.35 Write a procedure that
  computes elements of Pascal’s triangle by means of a recursive process.

  #+BEGIN_SRC clojure
    (defn pascal [row col]
      (cond
        (or (= 0 col) (= row col)) 1
        :else (+
               (pascal (- row 1) col)
               (pascal (- row 1) (- col 1)))))
  #+END_SRC

